Run functions and transformers on specific idea states
JetBrains/projector-client pull request #102
Opened 2021-11-17 18:18 UTC by ARTI1208

Allows to run code after specific IDE state occurred via `invokeWhenIdeaIsAtState` (previously known as `invokeWhenIdeaIsInitialized`). This change also allows to run transformers after different IDE states occurred.
Worth to note:
* Now all of the code that passed to `invokeWhenIdeaIsAtState` (or to new function `registerStateListener`) runs on one dedicated thread instead of spawning new threads on each `invokeWhenIdeaIsInitialized` invocation
* Now we can transform classes on different IDE states (for example, to fix PRJ-750 need to run transformer at BOOTSTRAP state) or even before IDE is loaded (or not loaded at all)
* There will be more logs (separate Successes, Skips and Errors for each state defined by transformers)

2021-11-23 21:30 UTC, SerVB requested changes
For some reason this PR is quite unclear and hard for me 😅

I'm asking some questions and propose a few changes.

2021-11-23 21:30 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +  thread(isDaemon = true) {
IMO, all this is quite low-level and not easy to understand. We can of course leave it as is for now, but at least for the future I propose the following changes:
1. Use coroutines instead of a thread. Maybe we could also get rid of the global constant `listenerThreadStarted` this way.
2. Change a low level `startingStateOrdinal` to just a clear enum value. We can still get its ordinal via a property.
3. Maybe use concurrent collections instead of a lock with condition, that could simplify code even more.

For now, I have no idea how we can test such code with many global variables...

2021-11-23 21:30 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +            val state = IdeaState.values()[i]
In the future, when we get rid of `startingStateOrdinal`, probably something simpler like `(startingState..IdeaState.values().last()).forEach { state ->` could work...

2021-11-23 21:30 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +    while (true) {
I'm wondering how we are supposed to go out of this loop.

Also, there is an active waiting without any sleep, right? Then it's quite ineffective.

2021-11-23 21:30 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaState.kt
> +      else -> throw IllegalStateException("IdeaState $name doesn't have backing com.intellij.diagnostic.LoadingState instance")
```suggestion
      else -> throw IllegalStateException("IdeaState $name doesn't have backing ${LoadingState::class.simpleName} instance")
```

2021-11-23 21:30 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaState.kt
> +      t.printStackTrace()
I think we better pass such calls in logger (there are also other such calls).

2021-11-30 09:15 UTC, ARTI1208 commented on projector-agent-common/src/main/kotlin/org/jetbrains/projector/agent/common/transformation/TransformerSetup.kt
> +  public fun getTransformations(): Map<Class<*>, (CtClass) -> ByteArray?> = emptyMap()
Now that transformers can be initialized before we retrieved IDE classloader referencing IDE classes too early leads to runtime exceptions, e.g. if in some transformer we have `classTransformations` property that is initialized by map with IDE class references instead of property with getter. So to prevent such problems I decided to switch from property to function. And swapping is here because functions go after properties

2021-11-30 09:17 UTC, ARTI1208 commented on projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IdeaTransformerSetup.kt
> +    get() = IdeaState.CONFIGURATION_STORE_INITIALIZED
It's unused in this PR, but will be required in future (to fix links handling on login screen, for example)

2021-11-30 09:31 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +public fun invokeWhenIdeaIsAtState(
Why do you like "ij" more? It doesn't make much sense to me if for example `IdeaState` becomes `IjState`

2021-11-30 09:36 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaState.kt
> +      else -> throw IllegalStateException("IdeaState $name doesn't have backing com.intellij.diagnostic.LoadingState instance")
This may throw ClassNotFoundException if we reached else branch before IDE classloader is retrieved, but I think it's legal since we should not reach this branch at all and already throw exception

2021-11-30 10:32 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaState.kt
> +      t.printStackTrace()
I think this particular one should be removed. The other one I'll fix

2021-11-30 11:00 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +  purpose: String?,
In previous implementation there was `onNoIdeaFound` parameter which disabled logging when was non-null (used only in DelegatingJvmLogger initailizer to prevent logging of "Staring attempts to.." and "Done <smthing>" on every logger instantiation which may be quite often) so I just adopted it by adding nullability

2021-11-30 11:28 UTC, SerVB commented on projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IdeaTransformerSetup.kt
> +    get() = IdeaState.CONFIGURATION_STORE_INITIALIZED
Could we maybe introduce this property only when needed and remove it from this PR then?

2021-11-30 11:33 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +public fun invokeWhenIdeaIsAtState(
"ij" is short for "IntelliJ Platform-based app", makes sense to me. All IDEs that we support are IntelliJ Platform-based apps, so the name matches the reality I would say.

We could also use "ijApp", for example. It's a bit more correct but a bit longer; still works. WDYT?

2021-11-30 11:34 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +  purpose: String?,
OK, but then I suggest to document it above the function.

2021-11-30 11:43 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +public fun invokeWhenIdeaIsAtState(
Interestingly, in my understanding "ij" refers to "IntelliJ Platform" as a framework, so the state (in a way it used in code) of framework has not much sense. May be we will agree on using "ide" instead for simplicity and unambiguity?

2021-11-30 11:50 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +public fun invokeWhenIdeaIsAtState(
> "ij" refers to "IntelliJ Platform" as a framework

True, but if it was without context. In our case, I though that it could be treated as "IJ-based app".

> May be we will agree on using "ide" instead for simplicity and unambiguity?

Cool, let's do it.

In general there can be a non-IDE app based on IntelliJ, but I hope it should be quite rare 😅

2021-11-30 11:50 UTC, ARTI1208 commented on projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IdeaTransformerSetup.kt
> +    get() = IdeaState.CONFIGURATION_STORE_INITIALIZED
If you're ok with re-reviewing this part once again some time after then yes...

2021-11-30 11:52 UTC, SerVB commented on projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IdeaTransformerSetup.kt
> +    get() = IdeaState.CONFIGURATION_STORE_INITIALIZED
OK

2021-11-30 11:53 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +public fun invokeWhenIdeaIsAtState(
Are there any at all?)

2021-11-30 15:17 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +    while (true) {
Do we actually want to go out of it? It's intended to be running all the time the server is up. So I think we just need make the thread non-daemon

2021-11-30 15:17 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +  thread(isDaemon = true) {
1. So am I right you propose to start a new coroutine for each new listener? In how many threads?
3. We still need the lock to block the thread when all listeners have finished, so the effect for code simplicity is not high. Also without the lock something may happen with global variables used in both threads

2021-12-28 14:56 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +    while (true) {
UPD. Added going out of the loop when all states are passed

2021-12-29 11:21 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeaStateUtils.kt
> +  thread(isDaemon = true) {
Ok, I rewrote it with coroutines and without global state. Looks nice now (but may be not that efficient as it was)

2022-01-12 17:45 UTC, ARTI1208 commented
@Avvessalom could you please take a look what happend here with dependencies downloading? I guess the problem is on github's side, but nevertheless

2022-01-17 14:18 UTC, olegchir approved these changes
This PR is so huge and there's a lot of changes.
I tried to read it for ~1h to understand it, first by diffing with the master, and then commit-by-commit.
I don't think I'm able to grasp everything, and only Artem knows better :) 

My question is about readability.
Maybe we should add some documentation to the new thing in the project?
For example, you add `ProjectorBatchTransformer` - maybe it's worth adding a couple of words what is it, what it is doing, why should we need this after all?

My concern here is that as times go by, it will be harder and harder to read and understand sources. We're not the only developers here, and someone will be here decades later, long after we leave the project. Adding comments may help.

2022-02-02 14:30 UTC, SerVB approved these changes
OK. Oleg, thank you for clarifying that the PR is difficult to review. However, for now it's not clear how we can avoid such PRs in the future... Maybe trying to split to separate PRs more...

The code documentation is quite complex topic because it's difficult to define how much comprehensive it should be. In this PR, it looks like it's pretty compact and can be extended, but it's better than nothing.

2022-02-08 08:48 UTC, merged