Various fixes primarily intended for Swing client
JetBrains/projector-client pull request #106
Opened 2021-11-23 22:32 UTC by knah

Individual commits provide more details on each specific fix

2021-11-24 09:46 UTC, ARTI1208 requested changes

2021-11-25 20:36 UTC, SerVB commented on projector-client-common/src/commonMain/kotlin/org/jetbrains/projector/client/common/canvas/CanvasFactory.kt
> +    override var height: Int = 1
I see it's just moved code from `projector-client-common/src/jvmMain/kotlin/org/jetbrains/projector/client/common/canvas/CanvasFactory.kt` file. So let's leave it like before.

I have another question about this class: do we need it in `main` source set? I see it's used only in tests, so maybe we could move it there?

2021-11-25 20:42 UTC, SerVB commented on projector-client-common/src/jsMain/kotlin/org/jetbrains/projector/client/common/canvas/DomContext2d.kt
> +      CompositeOperationType.DST
```suggestion
      CompositeOperationType.DST,
```

2021-11-25 20:42 UTC, SerVB commented on projector-client-common/src/commonMain/kotlin/org/jetbrains/projector/client/common/canvas/Context2d.kt
> +    DST
```suggestion
    DST,
```

2021-11-25 20:43 UTC, SerVB commented on projector-common/src/commonMain/kotlin/org/jetbrains/projector/common/protocol/toClient/WindowData.kt
> +  JWINDOW
```suggestion
  JWINDOW,
```

2021-11-25 20:47 UTC, SerVB commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/protocol/ManualJsonToClientMessageDecoder.kt
> +      this["p"] as Int?
Let's omit such minor codestyle suggestions in the future or just apply them youself if you want (what I just did).

Ideally, we should have a linter that tells us about such problems and allows us to save time.

2021-11-25 20:48 UTC, SerVB commented
Artem, please request my review after you finish here.

2021-11-29 14:44 UTC, knah commented on projector-client-common/src/commonMain/kotlin/org/jetbrains/projector/client/common/canvas/CanvasFactory.kt
> +    override var height: Int = 1
I've moved this class to test source set. With that, canvas size doesn't really matter for its test use, so keeping it at 1 is fine too.

2021-11-30 09:03 UTC, ARTI1208 commented
@knah if you are ready then re-request review here too

2021-11-30 17:25 UTC, ARTI1208 requested changes

2021-11-30 17:32 UTC, knah commented on projector-client-common/src/commonTest/kotlin/org/jetbrains/projector/client/common/misc/DummyCanvasFactory.kt
> + */
As a side note on this, this header was auto-generated by IDEA and collapsed. Not sure if it's some project configuration being wrong on my end, or if it needs to be committed to the repo to generate proper headers.

2021-11-30 17:37 UTC, ARTI1208 approved these changes

2021-11-30 18:28 UTC, SerVB commented on projector-client-common/src/commonTest/kotlin/org/jetbrains/projector/client/common/misc/DummyCanvasFactory.kt
> + */
> Not sure if it's some project configuration being wrong on my end, or if it needs to be committed to the repo to generate proper headers

Yep, this can currently happen if you open the client repo from the server repo: the settings are taken from the server. Actually, I've just though that this situation can be supported too, will take a look.

2021-11-30 19:34 UTC, SerVB approved these changes

2021-12-01 14:42 UTC, merged

2021-12-02 15:34 UTC, SerVB commented on projector-client-common/src/commonTest/kotlin/org/jetbrains/projector/client/common/misc/DummyCanvasFactory.kt
> + */
Should be fixed here: https://github.com/JetBrains/projector-server/commit/21048899ab3ef7317c23a72c2d4412be6d8b8b73