Symlinks in zip building
JetBrains/projector-client pull request #110
Opened 2021-11-29 15:00 UTC by Avvessalom

2021-11-30 09:00 UTC, ARTI1208 requested changes
Cool, now unsigned mac archives are smaller then windows and linux ones
May be we should make `createPackageZipTask` generic to specify how we archive only once (in case we change the underlying task in future)? Or maybe we should just remove unused configuration parameter, what do you think?

2021-11-30 12:25 UTC, Avvessalom commented on settings.gradle.kts
> +      classpath("org.paleozogt:symzip-plugin:0.10.1")
Sorry. I thought that hardcoding the version here would be a good idea since this plugin support has ended.
Fixed.

2021-11-30 12:25 UTC, Avvessalom commented on settings.gradle.kts
> +    id( "org.paleozogt.symzip") version "0.10.1" apply false
fixed

2021-11-30 12:26 UTC, Avvessalom commented on projector-launcher/build.gradle.kts
> +  id( "org.paleozogt.symzip")
fixed

2021-11-30 13:25 UTC, ARTI1208 approved these changes

2021-11-30 13:28 UTC, Avvessalom commented
> Approving, but you still haven't answered my question [#110 (review)](https://github.com/JetBrains/projector-client/pull/110#pullrequestreview-818690343) :)

I just remove unused configuration parameter)

2021-11-30 13:33 UTC, ARTI1208 commented
Oh, I somehow missed it..

2021-12-02 22:28 UTC, SerVB requested changes

2021-12-02 22:28 UTC, SerVB commented on settings.gradle.kts
> +  //todo: refactoring to make it look more elegant
Any ideas how? Looks like it's correct way. So I would remove the TODO...

2021-12-02 22:28 UTC, SerVB commented on projector-launcher/build.gradle.kts
> +  id( "org.paleozogt.symzip")
It's not...

2021-12-09 11:16 UTC, Avvessalom commented on settings.gradle.kts
> +  //todo: refactoring to make it look more elegant
I have no ideas, but it seems that it can be more elegant.

2021-12-13 09:19 UTC, SerVB approved these changes

2021-12-13 10:33 UTC, merged