Update dependencies
JetBrains/projector-client pull request #112
Opened 2021-12-01 16:40 UTC by ARTI1208

2021-12-01 18:17 UTC, ARTI1208 commented
I'm not sure about licenses it gradlew and gradlew.bat. @SerVB did you modify them the last time you updated wrapper?

2021-12-02 21:54 UTC, SerVB requested changes

2021-12-02 21:59 UTC, SerVB commented
> I'm not sure about licenses it gradlew and gradlew.bat. @SerVB did you modify them the last time you updated wrapper?

I remember some day IDEA inserted licenses to `gradlew`s and I removed them manually. But it was long ago and I don't remember the details.

When I update Gradle, I just change the version in `gradle/wrapper/gradle-wrapper.properties`, I don't update the scripts. If you think scripts should be updated too, feel free to do it. Regarding licenses, please just compare these files with original files...

2021-12-07 09:05 UTC, ARTI1208 commented
> IDEA inserted licenses

It looks it's not the case now, licenses appeared when I ran gradlew command to update wrapper


> I just change the version

For some reason it didn't work for me this time, but usually I do the same way

> Regarding licenses, please just compare these files with original files

What do you mean saying "original" files?

2021-12-07 12:08 UTC, ARTI1208 commented
Are integration tests broken?

2021-12-08 10:44 UTC, SerVB commented on projector-server-core/build.gradle.kts
> +      .exclude(group = "com.jetbrains.infra")
I don't know either. The changes you've just made LGTM, let's resolve this.

2021-12-08 10:46 UTC, SerVB commented
Probably because you've changed them. Do they work for you locally?

Btw, `ClickOptions.usingDefaultMethod()` seems suspicious: before it was `(5, 5)`. Maybe something like `ClickOptions.offset(5, 5)` will match the previous logic.

2021-12-08 10:48 UTC, SerVB approved these changes
@Avvessalom , could you please help here?
1. With int tests failing.
2. Qodana reports places unrelated to this PR, maybe we can submit it as a piece of feedback to the Team.

2021-12-08 15:12 UTC, ARTI1208 commented
> Btw, ClickOptions.usingDefaultMethod() seems suspicious
These integration tests are passing with this param. `(5, 5)` was only needed to avoid using `click()` without arguments (as suggests comment), so `(5, 5)` and `ClickOptions.usingDefaultMethod()` essentialy play the same role here

2021-12-22 13:24 UTC, Avvessalom approved these changes

2021-12-22 17:57 UTC, merged