PRJ-127 Show alert with copied text when asynchronous clipboard API is not available
JetBrains/projector-client pull request #114
Opened 2021-12-08 17:36 UTC by ARTI1208

2021-12-13 11:12 UTC, SerVB requested changes
Works for me in a browser perfectly but doesn't work in Electron. Could you please investigate? Maybe that `catch` happens, so prompt isn't executed...

2021-12-13 11:13 UTC, SerVB commented
Also, some tests failed, I've just rerun them, maybe it will fix them...

2021-12-18 11:51 UTC, ARTI1208 commented on docSrc/src/doc/docs/ij_user_guide/accessing.md
> +| [Client app ("launcher")](#client-app-launcher) | Windows, Linux, MacOS |
Markdown plugin suggested this change (so it can provide UI to manipulate rows etc. I guess). Also I think it can be easier read this way without preview. I'll remove this from PR though as it is unrelated, but we should consider this later

2021-12-18 14:00 UTC, ARTI1208 commented
Found out that in electron window.prompt is not implemented, that's why it didn't work (and threw exception). There is no easy way to superseed this - other standart dialogs don't allow copying, and as we wanted to implement client-side non-blocking windows/dialogs in the future I don't want to use libraries to make it work in this PR. So for now just prevented exceptions when running in electron

2022-02-03 11:15 UTC, SerVB commented on docSrc/src/doc/docs/ij_user_guide/accessing.md
> +| [Client app ("launcher")](#client-app-launcher) | Windows, Linux, MacOS |
Ok, added to discuss on the weekly meeting

2022-02-03 11:22 UTC, SerVB approved these changes

2022-02-03 11:22 UTC, SerVB commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/ClipboardHandler.kt
> +  }
Something like a chain pattern can be applied here to split implementations and define clearer logic what's going on after what. Also, splitting can make the implementations testable more easy.

Of course we can postpone it until we have time to write tests for copying.

2022-03-15 08:05 UTC, merged