PRJ-771 redo work with npm
JetBrains/projector-client pull request #123
Opened 2022-01-18 10:11 UTC by Avvessalom

[ticket link](https://youtrack.jetbrains.com/issue/PRJ-771)

This pull request reworks the work with npm. Now the node and npm will be installed during the build of the project, and not use those already installed in the system.

2022-02-03 14:30 UTC, SerVB requested changes
So preinstalling some software isn't needed now? Cool! Let's update the Prerequisites section in readme then.

The code can be improved.

2022-02-04 08:30 UTC, Avvessalom commented on projector-launcher/build.gradle.kts
> +val node = if (isFamily(Os.FAMILY_WINDOWS)) {
I made it so that when writing the command it reads like the normal spelling of npm, node

2022-02-04 09:05 UTC, Avvessalom commented on projector-launcher/build.gradle.kts
> +import org.apache.tools.ant.taskdefs.condition.Os.isFamily
this one is more compact, the line is shorter and more readable

2022-02-07 20:03 UTC, SerVB commented on projector-launcher/build.gradle.kts
> +import org.apache.tools.ant.taskdefs.condition.Os.isFamily
Well, I don't think that it's more readable now. Also, two imports are needed now. The argument that it's more compact is correct, but do we need compact code or clear one? I would leave it as it was... Probably extracting a function like `isWindows`.

Let's ask @ARTI1208 to give us his opinion.

2022-02-07 20:11 UTC, SerVB commented on projector-launcher/build.gradle.kts
> +}
Speaking of refactoring and making code shorter in terms of removing duplicated or unneeded code, I would suggest the following changes:

```suggestion
val nodeDir get() = kotlinNodeJsSetupTask.destination

val nodeCommand = when (isFamily(Os.FAMILY_WINDOWS)) {
  true -> nodeDir.resolve("node.exe")
  false -> nodeDir.resolve("bin/node")
}
```

Also, it replaces `if` with `when` as it was before (and it's better to avoid changing such stuff if it's already written and there is no clear advantage of changing it).

2022-02-07 20:12 UTC, SerVB commented on projector-launcher/build.gradle.kts
> +val kotlinNodeJsSetupTask = rootProject.tasks.getByName<NodeJsSetupTask>("kotlinNodeJsSetup")
Why do you think this variant is better than the last one I've suggested? Fmpov, it's good to have the name of the task only a single time here.

```suggestion
val kotlinNodeJsSetup: NodeJsSetupTask by rootProject.tasks
```

2022-02-07 20:17 UTC, SerVB commented on projector-launcher/build.gradle.kts
> +tasks.create<Exec>("electronBuildAndRun") {
Why is ordering here changed? The diff becomes broken... It's better to leave the ordering as it was...

2022-02-08 10:18 UTC, Avvessalom commented on projector-launcher/build.gradle.kts
> +tasks.create<Exec>("electronBuildAndRun") {
yes, sorry about that. I changed the order so that it is in alphabetical order so that the order is the same as in the gradle view

2022-02-09 12:00 UTC, SerVB commented on projector-launcher/build.gradle.kts
> +tasks.create<Exec>("electronBuildAndRun") {
The problem in such changes is that diff doesn't help to understand what's really changed. Looks like it's better to split changing (switching to nodejstask in our case) and reordering. Reordering can be done in a separate PR or even directly in master branch if you are sure about it.

For now, since some changes happened here, looks like it violates what's written here now: https://github.com/JetBrains/projector-client/commit/eb3bf403bcae6809e2c8ac319743fea0cc74b982

2022-02-09 12:00 UTC, SerVB commented on projector-launcher/build.gradle.kts
> +val npmCommand = when(DefaultNativePlatform.getCurrentOperatingSystem().isWindows) {
Incorrect formatting. Why doesn't Qodana see it?

2022-02-09 14:29 UTC, SerVB approved these changes

2022-02-10 08:06 UTC, merged