Prj 773 switch to kotest. Small jvm modules tests refactoring
JetBrains/projector-client pull request #128
Opened 2022-02-07 12:51 UTC by Avvessalom

Rewriting tests in small jvm modules.

- projector-ij-common

2022-02-16 10:55 UTC, ARTI1208 requested changes

2022-02-16 10:55 UTC, ARTI1208 commented on projector-util-loading/src/test/kotlin/org/jetbrains/projector/util/loading/ReflectionTest.kt
> +    test("field should be able to become unprotected") {
Better to name something like "final field can be unprotected". There are additional steps for final fields, so better specify `final` here then `non-final` in next test

2022-02-16 10:55 UTC, ARTI1208 commented on projector-util-loading/src/test/kotlin/org/jetbrains/projector/util/loading/ReflectionTest.kt
> +    test("non-final field should be able to become unprotect") {
Also better to name something like "field can be unprotected"

2022-02-21 20:19 UTC, SerVB requested changes
For JVM, could we use annotation spec to minimize the diff? Or do you see any advantages of fun spec?

2022-02-22 07:35 UTC, Avvessalom commented
Certainly, we can use Annotations spec. The Fun spec is chosen here for test uniformity, since Annotations spec does not work in multiplatform modules.

2022-02-24 12:05 UTC, Avvessalom commented
I rewrote everything on the Annotations spec. I think now the diff is as readable as possible.

2022-02-26 18:43 UTC, ARTI1208 requested changes
Looks nice

I see that IDEA marks test functions as unused, guess we should report this
![изображение](https://user-images.githubusercontent.com/31630000/155855258-eb27722a-e96e-47a7-8fd3-15b14a270c6b.png)

2022-02-26 18:43 UTC, ARTI1208 commented on projector-util-loading/build.gradle.kts
> +val kotestVersion: String by project
Move this version near the other ones pls

2022-03-14 16:53 UTC, SerVB approved these changes

2022-03-14 16:53 UTC, SerVB commented on projector-ij-common/src/test/kotlin/org/jetbrains/projector/agent/init/IjArgsTest.kt
> +    map.size shouldBe 5
```suggestion
    map shouldHaveSize 5
```

2022-03-15 08:36 UTC, ARTI1208 approved these changes

2022-03-15 09:53 UTC, merged