Prj 773 switch to kotest. MP modules tests refactoring
JetBrains/projector-client pull request #129
Opened 2022-02-08 13:44 UTC by Avvessalom

Rewriting tests in MP modules.

- projector-client-common

2022-02-16 12:26 UTC, ARTI1208 requested changes

2022-02-16 12:26 UTC, ARTI1208 commented on projector-client-common/src/commonTest/kotlin/org/jetbrains/projector/client/common/SingleRenderingSurfaceProcessorTest.kt
> +    test("shrink function should be work with events") {
```suggestion
    test("shrink function should work with events") {
```

2022-02-16 12:26 UTC, ARTI1208 commented on projector-client-common/src/commonTest/kotlin/org/jetbrains/projector/client/common/SingleRenderingSurfaceProcessorTest.kt
> +    test("shrink function should be work with paint events") {
```suggestion
    test("shrink function should work with events with prerequisites") {
```

2022-02-27 09:41 UTC, ARTI1208 approved these changes

2022-03-21 18:11 UTC, SerVB commented
We decided to postpone it, probably we will get a reply from kotest. Let me remove me from reviewers for now to clear UI for me

2023-01-09 11:44 UTC, closed without merging