Prj 773 switch to kotest. Projector-client-web
JetBrains/projector-client pull request #131
Opened 2022-02-11 13:54 UTC by Avvessalom

Rewriting tests in projector-client-web

2022-02-16 12:06 UTC, ARTI1208 approved these changes

2022-02-21 20:10 UTC, SerVB requested changes
Cool but can be improved in some place.

Let's have a call and discuss

2022-02-22 13:06 UTC, SerVB commented on projector-client-web/src/test/kotlin/org/jetbrains/projector/client/web/input/key/ImeTest.kt
> +    xtest("windows should be able to type \"Alt end dash\"") {
"alt + 0150" on Windows should give En Dash

2022-03-21 18:11 UTC, SerVB commented
We decided to postpone it, probably we will get a reply from kotest. Let me remove me from reviewers for now to clear UI for me

2023-01-09 11:44 UTC, closed without merging