Allow disabling server integrations with IDE
JetBrains/projector-client pull request #140
Opened 2022-03-22 11:42 UTC by SerVB

A new server option is added.

Paired PR: TODO

2022-03-22 16:36 UTC, ARTI1208 requested changes

2022-03-22 16:36 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeState.kt
> +      get() = attachToIde ?: try {
It will cause exception when no IDE attached
`java.lang.ClassNotFoundException: com.intellij.ide.WindowsCommandLineProcessor`
Is it intended? If not, may be change as follows?

```suggestion
      get() = attachToIde.takeIf { it != true } ?: try {
```

2022-03-22 16:56 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeState.kt
> +      get() = attachToIde ?: try {
Indeed the exception will happen if a user explicitly specified the `true` value before running with a not-ij-based app. Do you think it's a problem and we should provide safety code that you suggest for that situation?

2022-03-22 16:57 UTC, SerVB commented on docSrc/src/doc/docs/ij_user_guide/server_customization.md
> +!!! warning With default Projector distribution, this will leave you with no way to connect to it. This option is intended primarily for use
Thanks for noticing it! Wasn't intended.

2022-03-22 18:14 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/state/IdeState.kt
> +      get() = attachToIde ?: try {
I think yes

2022-03-28 15:00 UTC, knah requested changes
I believe `IjInjectorAgentInitializer` (and, in general, agent attach) should also be gated by this setting - I didn't find it checking for `isIdeAttached` anywhere.

2022-03-28 17:34 UTC, SerVB commented
@knah, added https://github.com/JetBrains/projector-server/pull/119/commits/ca9b3dfdb870e847bcabdff332f0e4179054916d. OK?

@ARTI1208, that's why JDK17 transformer should be avoided or extracted from IJ transformer somehow. If you have any ideas, please share.

2022-03-28 17:39 UTC, knah approved these changes

2022-03-29 10:25 UTC, ARTI1208 approved these changes
> JDK17 transformer should be avoided

I don't believe this is possible, they removed the ability to specify Toolkit and other things via properties, so that only original implementation could be used. So either transformer is need or modified JDK

> extracted from IJ transformer somehow. If you have any ideas, please share

We can pass the flag to agent so that transformers can choose whether they should be executed when we disable integrations with IDE. Or extract all non-ide-related transformers, as you stated

2022-03-29 10:38 UTC, SerVB commented
> they removed the ability to specify Toolkit and other things via properties, so that only original implementation could be used

That's pity. We should report that (not right now, but we should)

2022-03-29 11:05 UTC, merged