PRJ-373: Relay server support
JetBrains/projector-client pull request #26
Opened 2021-05-26 13:58 UTC by IKrukov-HORIS

2021-06-01 14:53 UTC, SerVB requested changes

2021-06-01 14:53 UTC, SerVB commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/websocket/HttpWsServer.kt
> +      logger.info { "Server started on host $host and port $port" }
Can we add the same message to relay server?

2021-06-01 14:53 UTC, SerVB commented on projector-client-common/src/jsMain/kotlin/org/jetbrains/projector/client/common/misc/ParamsProvider.kt
> +  val ENABLE_RELAY: Boolean
Please add a very brief description of these to parameters to the end of the list: https://github.com/JetBrains/projector-client/tree/master/projector-client-web#debugtest-parameters

2021-06-02 10:23 UTC, IKrukov-HORIS commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/websocket/HttpWsServer.kt
> +      logger.info { "Server started on host $host and port $port" }
Sure. I've added logger and connection message to HttpWsClient.

2021-06-02 11:10 UTC, IKrukov-HORIS commented on projector-client-common/src/jsMain/kotlin/org/jetbrains/projector/client/common/misc/ParamsProvider.kt
> +  val ENABLE_RELAY: Boolean
Done

2021-06-07 16:13 UTC, SerVB commented on projector-client-web/README.md
> +`serverId` | String? | Not present | Identifier of Projector server to connect to, when relay is used.
Now it seems like we can merge these two parameters into single like `relayServerId: String?`

2021-06-08 09:56 UTC, IKrukov-HORIS commented on projector-client-web/README.md
> +`serverId` | String? | Not present | Identifier of Projector server to connect to, when relay is used.
Agreed. Fixed.

2021-06-08 11:15 UTC, merged