Cicd running tests on all os
JetBrains/projector-client pull request #30
Opened 2021-07-12 10:06 UTC by Avvessalom

2021-07-14 12:56 UTC, SerVB requested changes
Let's also add some badges to README.

2021-07-14 12:56 UTC, SerVB commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
Why don't we build on other platforms?

2021-07-14 12:56 UTC, SerVB commented on .github/workflows/test.yml
>        - run: ./gradlew check build
I guess we should make configurations consistent between repos. [Here](https://github.com/JetBrains/projector-server/pull/34/files) we've split check and build to two different workflows.

2021-07-15 07:03 UTC, Avvessalom commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
they were commented out, but I removed them later. For Windows and Mac, build does not work now

2021-07-15 07:05 UTC, Avvessalom commented on .github/workflows/test.yml
>        - run: ./gradlew check build
yes, it will probably be correct. earlier in this repository, I split, but after that I even returned it as it was

2021-07-15 07:07 UTC, Avvessalom commented
if after the corrections the PR suits you, please do not confirm, I need to correct the commit history

2021-07-16 09:01 UTC, Avvessalom commented
@SerVB please fix the merge conflict, I do not have enough access

2021-07-19 09:56 UTC, SerVB requested changes
Well, you should fix the conflict locally (probably via rebasing to the origin/master and force pushing here). Feel free to DM me if you need help with this.

2021-07-20 13:30 UTC, SerVB requested changes

2021-07-20 13:30 UTC, SerVB commented on .github/workflows/build.yml
> +#            ./gradlew :projector-launcher:distZip
Can we at least build OS-specific variants like `:packageZipDarwinX64` and `:packageZipWin32X64` on these OSes?

2021-07-22 17:01 UTC, SerVB approved these changes

2021-07-22 17:01 UTC, merged