Use Map to pass and read agent arguments
JetBrains/projector-client pull request #31
Opened 2021-07-12 10:27 UTC by ARTI1208

Allows passing arguments to `ClassFileTransformer` instances in a form of a map, eliminating the task of modifying `projector-agent-ij-injector/org.jetbrains.projector.agent.ijInjector.IjInjectorAgent` and `projector-agent-ij-injector/org.jetbrains.projector.agent.ijInjector.IjInjector` each time new arguments are added or obsolete are removed.

2021-07-13 10:04 UTC, SerVB requested changes

2021-07-13 10:04 UTC, SerVB commented on projector-agent-common/build.gradle.kts
> +  api(project(":projector-common"))
Well, this module is quite big, I think it's redundant to include it as a whole. Let's create one more module like `projector-agent-initializer`.

2021-07-13 10:04 UTC, SerVB commented on projector-common/src/jvmMain/kotlin/org/jetbrains/projector/common/ij/IjArgs.kt
> +}
Let's create some unit tests for these methods.

2021-07-13 11:06 UTC, ARTI1208 commented on projector-agent-common/build.gradle.kts
> +  api(project(":projector-common"))
Done

2021-07-13 11:06 UTC, ARTI1208 commented on projector-common/src/jvmMain/kotlin/org/jetbrains/projector/common/ij/IjArgs.kt
> +}
Done

2021-07-14 12:42 UTC, SerVB approved these changes

2021-07-14 12:42 UTC, merged