Skip speculative rendering of potentially invisible inputted chars
JetBrains/projector-client pull request #37
Opened 2021-07-15 12:05 UTC by ARTI1208

Potentially invisible inputted chars:

- Chars with unicode category from "Other" group: UNASSIGNED (Cn), CONTROL (https://www.compart.com/en/unicode/category/Cc), FORMAT (https://www.compart.com/en/unicode/category/Cf), PRIVATE_USE (Co), SURROGATE (Cs)  (Example: pressing Esc or Meta  produced rendering of invalid char)
- Chars inputted with any of Ctrl/Alt/Meta modifiers (Example: Ctrl+C produced rendering of 'c')

2021-07-15 13:35 UTC, SerVB requested changes
Good catch, but I have some concerns on clarity. Maybe more clear check will be better. And maybe there should be a comment explaining which symbols we need to show on the screen and which to ignore.

2021-07-15 13:35 UTC, SerVB commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/speculative/Typing.kt
> +          || event.char.category.code.startsWith('C')) return
This `event.char.category.code.startsWith('C')` looks quite unclear. Could we maybe check `event.char.category in someSet`? Should be more clearer. Also, I think this check should better be extracted to a function like `Char.isVisible` with some tests ;)

2021-07-15 14:25 UTC, ARTI1208 commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/speculative/Typing.kt
> +          || event.char.category.code.startsWith('C')) return
`this check should better be extracted`
Do you mean the part `event.char.category ...` or the entire if?

2021-07-19 09:46 UTC, SerVB commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/speculative/Typing.kt
> +          || event.char.category.code.startsWith('C')) return
> Do you mean the part event.char.category ... or the entire if?

I guess the part. And for the entire check, it can be another function, if you want. But I don't want to be a ruler :) Just imagine that you read this code a year after: will it be clear to you? what can be done to make it clearer?

I'm just trying to think in terms of understandability and testability and it seems some functions extractions are needed here.

2021-07-23 10:15 UTC, ARTI1208 commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/speculative/Typing.kt
> +          || event.char.category.code.startsWith('C')) return
Yeah, I got your point, made category check more clear. I don't think unit tests make sense in this case as the check is rather trivial (just checks some value is in the set/list)

2021-07-28 11:40 UTC, SerVB approved these changes

2021-07-28 11:41 UTC, merged