Use custom classloader for server and agent jvm code
JetBrains/projector-client pull request #46
Opened 2021-07-23 17:05 UTC by ARTI1208

Custom classloader that delegates classloading to appropriate one: IDE classloader or AppClassLoader. This allows direct referencing of classes from intellij platform. Example in projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IjInjector.kt accesses class com.intellij.openapi.extensions.ExtensionPointName

Doesn't work for classes from plugins (Maybe later)
TODO: fix crash when using Projector plugin

2021-07-29 11:29 UTC, ARTI1208 commented
Eh, Qodana doesn't know we have projector-server depending on this repo and reports many false positive "Redundant visibility modifier" (and one "Function is never used")

2021-08-03 13:17 UTC, SerVB requested changes
> Qodana doesn't know we have projector-server depending on this repo and reports many false positive "Redundant visibility modifier" (and one "Function is never used")

I think we should do something from our side here since we just have a non-standard project split. I suggest adding suppresses and comments why the suppresses are needed (I've marked some places but there are more).

2021-08-03 13:17 UTC, SerVB commented on projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IjInjectorAgent.kt
> +@Suppress("unused")
Let's leave a comment why this suppression is needed

2021-08-03 13:17 UTC, SerVB commented on projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IjInjector.kt
> +  @Suppress("unused")
Let's leave a comment why this suppression is needed

2021-08-03 13:17 UTC, SerVB commented on projector-agent-ij-injector/src/main/kotlin/org/jetbrains/projector/agent/ijInjector/IjInjectorAgent.kt
> +      .invoke(null, instrumentation, argsMap)
I think a small comment of what's happening here will be useful for the future.

2021-08-03 13:17 UTC, SerVB commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/classloader/Setup.kt
> +public fun initClassLoader(classLoader: ClassLoader): ClassLoader {
Let's suppress it with a comment why it's needed to be public and unused

2021-08-03 13:17 UTC, SerVB commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/classloader/Setup.kt
> +  // accessed in agent to get ide ana projector classloaders in platform classloader context
```suggestion
  // accessed in agent to get ide and projector classloaders in platform classloader context
```

2021-08-03 13:17 UTC, SerVB commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/ij/IjInjectorAgentInitializer.kt
> +  @Suppress("unused")
Let's add a comment why it's needed to be suppressed

2021-08-03 13:17 UTC, SerVB commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/ProjectorClassLoader.kt
> +public class ProjectorClassLoader constructor(parent: ClassLoader? = null) : ClassLoader(parent) {
Wow, that's huge! I suggest adding a separate page to developer documentation describing the logic. Probably this class and `initClassLoader` should receive attention.

2021-08-03 17:25 UTC, ARTI1208 commented on projector-util-loading/src/main/kotlin/org/jetbrains/projector/util/loading/ProjectorClassLoader.kt
> +public class ProjectorClassLoader constructor(parent: ClassLoader? = null) : ClassLoader(parent) {
> separate page to developer documentation

Do you mean a page under "Projector internal documentation" in Space? Or at public documentation under "Developer guide" section (if that's the thing then how?)?

2021-08-09 18:50 UTC, SerVB approved these changes
Cool, I have only a small suggestion.

2021-08-09 18:50 UTC, SerVB commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/ij/IdeaState.kt
> +            onInitialized?.invoke(ideaClassLoader)
Am I right that here we imply that `onClassLoaderFetched == null` and `onInitialized != null`? Then I suggest at least marking this in code:

```suggestion
            onInitialized!!(ideaClassLoader)
```

Minor: since now there is one more parameter in the function, maybe it's worth to finally describe its expected logic in the javadoc.

2021-08-09 19:17 UTC, ARTI1208 commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/ij/IdeaState.kt
> +            onInitialized?.invoke(ideaClassLoader)
Ah, yeah, it will loop infinitely if we use it with IDEA and both `onClassLoaderFetched` and `onInitialized` are null, good notice

Do you think doc for the function should be added in this PR?

2021-08-09 20:44 UTC, SerVB commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/ij/IdeaState.kt
> +            onInitialized?.invoke(ideaClassLoader)
Yeah, let's add it now.

2021-08-10 08:39 UTC, ARTI1208 commented on projector-server-core/src/main/kotlin/org/jetbrains/projector/server/core/ij/IdeaState.kt
> +            onInitialized?.invoke(ideaClassLoader)
Fixed and added javadoc

2021-08-10 19:32 UTC, merged