Get rid of md plugin requirement
JetBrains/projector-client pull request #47
Opened 2021-07-26 20:59 UTC by cute-jumper

Markdown plugin is not installed on some IDEA-based IDE (such as Android Studio). For `IjMdTransformer`, we should capture the exception if the markdown plugin is not installed. For other transforms, it is safer to use searcheverywhere EP instead since there should be at least one implementation from the IDE itself.

2021-07-27 12:01 UTC, SerVB requested changes
Thank you for resolving the TODO! I have only some minor suggestions

2021-07-27 23:46 UTC, cute-jumper commented
Thanks for the review! Updated the variable names

2021-07-28 11:38 UTC, SerVB approved these changes

2021-07-28 18:01 UTC, SerVB commented
Let's wait until checks are passing. For some reason, they are in queue...

2021-08-02 17:51 UTC, merged