Ci publish on space
JetBrains/projector-client pull request #57
Opened 2021-08-11 08:45 UTC by Avvessalom

2021-08-11 14:40 UTC, Avvessalom commented
before merging with master, need to change the repositories links to `intelij-dependencies`

2021-08-12 16:03 UTC, ARTI1208 commented on buildSrc/src/main/kotlin/publishOnSpace.kt
> +  if (fromComponents.equals("java", false)) {
'false' is default value, no need to explicitly specify it

2021-08-12 16:11 UTC, ARTI1208 commented on buildSrc/src/main/kotlin/publishOnSpace.kt
> +fun Project.publishOnSpace(publishingExtension: PublishingExtension, fromComponents: String) {
May be it's better to swap Project and PublishingExtension? Seems more natural as it is used inside publishing closure. Also, whether 'fromComponentS' should be 'fromComponent' or String be some kind of container of Strings?

2021-08-16 13:44 UTC, SerVB requested changes

2021-08-16 13:44 UTC, SerVB commented on .github/workflows/publish-on-space.yml
> +          echo publishingVersion=${{ github.sha }} | head -c 26 >> gradle.properties
Here we depend on the length of "publishingVersion=" and it's error-prone. Let's use just the length of the hash we want to use: `8`. So I guess it will be something like:

```suggestion
          publishingVersion=${{ github.sha }} | head -c 8
          echo publishingVersion=$publishingVersion >> gradle.properties
```

2021-08-16 13:44 UTC, SerVB commented on buildSrc/src/main/kotlin/publishOnSpace.kt
> +  if (fromComponent.equals("java")) {
```suggestion
  if (fromComponent == "java") {
```

2021-08-17 10:04 UTC, Avvessalom commented on .github/workflows/publish-on-space.yml
> +          echo publishingVersion=${{ github.sha }} | head -c 26 >> gradle.properties
I can just add zero terminated row with version
```shell
echo publishingVersion= | head -c 18 -z >> gradle.properties
echo ${{ github.sha }}  | head -c 8 >> gradle.properties
```

2021-08-17 11:55 UTC, Avvessalom commented on .github/workflows/publish-on-space.yml
> +          echo publishingVersion=${{ github.sha }} | head -c 26 >> gradle.properties
fixed with `echo -n`

2021-08-18 14:11 UTC, SerVB approved these changes
Cool, so should we now fix the repo path?

2021-08-18 14:25 UTC, Avvessalom commented
> Cool, so should we now fix the repo path?

yes. Already fixed

2021-08-18 14:45 UTC, ARTI1208 approved these changes

2021-08-18 15:11 UTC, merged