Refactoring move jacoco reports to buildSrc
JetBrains/projector-client pull request #62
Opened 2021-08-16 08:33 UTC by Avvessalom

2021-08-17 14:23 UTC, ARTI1208 requested changes

2021-08-17 14:23 UTC, ARTI1208 commented on buildSrc/src/main/kotlin/jacocoReport.kt
> +fun JacocoReport.jacocoReport(project: Project, moduleName: String, kotlinJsModule: Boolean = false) {
`JacocoReport.jacocoReport`.. It feels strange to me, may be rename function to something like `setupReporting`?

2021-08-17 14:23 UTC, ARTI1208 commented on buildSrc/src/main/kotlin/jacocoReport.kt
> +  }
```suggestion
  }

```

2021-08-17 14:23 UTC, ARTI1208 commented on projector-agent-common/build.gradle.kts
> +  jacocoReport(project, "Projector-agent-common")
Why not use previous module camelCase naming (like AgentCommon on line 37 here)? Using kebab-case in module name produces filename with a weird mix of camelCase and kebab-case (jacocoHtmlProjector-agent-common). The same for other module names

2021-08-24 12:05 UTC, SerVB requested changes
It can be improved

2021-08-24 12:05 UTC, SerVB commented on buildSrc/src/main/kotlin/jacocoReport.kt
> +    xml.outputLocation.set(project.file(project.layout.buildDirectory.dir("../../JacocoReports/jacocoReport$moduleName.xml")))
I think the following is more concise, but not sure if it works:

```suggestion
    xml.outputLocation.set(project.rootProject.file("JacocoReports/jacocoReport$moduleName.xml"))
```

2021-08-24 12:05 UTC, SerVB commented on projector-util-loading/build.gradle.kts
> +  toolVersion = "0.8.7"
Can we at least move this version to a constant, or maybe even move this whole `jacoco {}` block to buildSrc?

2021-08-24 12:05 UTC, SerVB commented on projector-util-loading/build.gradle.kts
> +  setupReporting(project, "ProjectorUtilLoading")
By the way, can we move `tasks.withType<JacocoReport> {` inside `setupReporting`?

2021-08-24 13:06 UTC, Avvessalom commented on projector-util-loading/build.gradle.kts
> +  setupReporting(project, "ProjectorUtilLoading")
yes, but if we remove this task and leave the only function, all `finalizedBy` tasks won't work

2021-08-24 13:20 UTC, Avvessalom commented on projector-util-loading/build.gradle.kts
> +  toolVersion = "0.8.7"
> Can we at least move this version to a constant

forgot about it. I will add to gradle.properties

>or maybe even move this whole jacoco {} block to buildSrc?

no, we have to configure jacoco regardless of this task

2021-08-25 12:44 UTC, ARTI1208 requested changes

2021-08-25 12:44 UTC, ARTI1208 commented on projector-client-common/build.gradle.kts
> +  setupReporting(project, isKotlinMpModule=true)
```suggestion
  setupReporting(project, isKotlinMpModule = true)
```

2021-08-25 12:44 UTC, ARTI1208 commented on projector-common/build.gradle.kts
> +  setupReporting(project, isKotlinMpModule=true)
```suggestion
  setupReporting(project, isKotlinMpModule = true)
```

2021-09-08 13:17 UTC, SerVB commented on projector-common/build.gradle.kts
> +  setupReporting(project, isKotlinMpModule=true)
I would suggest don't bother much with codestyle. We should set up an automatic linter instead.

2021-09-20 18:21 UTC, SerVB approved these changes

2021-09-21 15:02 UTC, merged