fix failing int test due jacoco plugin
JetBrains/projector-client pull request #63
Opened 2021-08-17 13:58 UTC by Avvessalom

[fix](https://github.com/gradle/gradle/issues/16841)

2021-08-19 16:11 UTC, SerVB requested changes

2021-08-19 16:11 UTC, SerVB commented on projector-server-core/build.gradle.kts
> +System.setProperty("user.dir", projectDir.toString())
This place looks kinda random for me. Could we place it inside the main build.gradle in subprojects and also make a comment why it's needed?

2021-08-24 09:33 UTC, Avvessalom commented on projector-server-core/build.gradle.kts
> +System.setProperty("user.dir", projectDir.toString())
> Could we place it inside the main build.gradle in subprojects 

no, we couldn't. it wouldn't work

2021-08-24 09:50 UTC, Avvessalom commented
I checked tests in other modules, they don't trigger this error yet. Moved the property to a more logical location and added an explaining comment

2021-08-25 13:58 UTC, SerVB approved these changes

2021-08-25 13:58 UTC, merged