PRJ-443 Remove "Allow popups for this site" alert when allowance is not needed
JetBrains/projector-client pull request #97
Opened 2021-11-01 15:23 UTC by ARTI1208

Removes alert when using projector-launcher or when opening local file

2021-11-03 10:42 UTC, Avvessalom requested changes
please update the changelog

2021-11-03 10:53 UTC, ARTI1208 commented
@Avvessalom [done in projector-server](https://github.com/JetBrains/projector-server/pull/88/files#diff-5a046b40ddd70d458429a37725fee2e111b39034ae1c51932507019fc51ecea9) (it is client-wide change, not launcher-specific)

2021-11-03 11:08 UTC, Avvessalom approved these changes

2021-11-09 11:08 UTC, SerVB requested changes
Great, I've checked it, the pop up isn't shown now. I even didn't remember that it's our own pop up, I though it's from Electron side.

The code could be improved.

Also, code related to opening an URL is quite complex now, maybe it's worth extracting it from ServerEventsProcessor to a new place like UriOpener?

2021-11-09 11:10 UTC, SerVB commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/ServerEventsProcessor.kt
> +      logger.info { "Link wasn't handled" }
I mean the naming could be improved.

2021-11-16 11:01 UTC, ARTI1208 commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/ServerEventsProcessor.kt
> +    }
Firefox can throw exception when opening a local file

2021-11-16 11:04 UTC, ARTI1208 commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/electron/ElectronUtils.kt
> +  }
1. Done
2. Done
3. process is exposed from Node.js and Electron, so I guess that's unreasonable to make a ticket for Kotlin/JS. Also there is no Kotlin wrapper neither for Node.js nor for Electron..

2021-11-16 11:05 UTC, ARTI1208 commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/ServerEventsProcessor.kt
> +  }
I can't come up with a good name too, so ended up with entirely removing this function)

2021-11-16 11:47 UTC, ARTI1208 commented on projector-common/src/commonMain/kotlin/org/jetbrains/projector/common/protocol/toClient/ServerEvent.kt
> +@Suppress("unused") //used in client-web/org.jetbrains.projector.client.web.ServerEventsProcessor and at server side
Now Qodana complains about unused symbol..

2021-11-17 13:56 UTC, SerVB commented on projector-common/src/commonMain/kotlin/org/jetbrains/projector/common/protocol/toClient/ServerEvent.kt
> +@Suppress("unused") //used in client-web/org.jetbrains.projector.client.web.ServerEventsProcessor and at server side
Like in #100, looks like Qodana bug (there is no warning in IDE, right?). So let's forget about Qodana in this case.

2021-11-17 14:00 UTC, SerVB approved these changes
LGTM

2021-11-17 14:13 UTC, SerVB commented on projector-client-web/src/main/kotlin/org/jetbrains/projector/client/web/electron/ElectronUtils.kt
> +  }
3. There is the [KT-35327 Support Electron in Kotlin JS Gradle plugin](https://youtrack.jetbrains.com/issue/KT-35327). I would suggest to create a ticket about our use case and attach to KT-35327 as related. So Kotlin team will see that such use case exists.

> there is no Kotlin wrapper neither for Node.js nor for Electron

That's strange because I've heard Kotlin supports targeting Node.js.

2021-11-17 18:25 UTC, ARTI1208 commented on projector-common/src/commonMain/kotlin/org/jetbrains/projector/common/protocol/toClient/ServerEvent.kt
> +@Suppress("unused") //used in client-web/org.jetbrains.projector.client.web.ServerEventsProcessor and at server side
A month or more ago you proposed to suppress places like this, so I did that way. Glad that now I can forget about such cases)

2021-11-18 09:14 UTC, SerVB commented on projector-common/src/commonMain/kotlin/org/jetbrains/projector/common/protocol/toClient/ServerEvent.kt
> +@Suppress("unused") //used in client-web/org.jetbrains.projector.client.web.ServerEventsProcessor and at server side
Yep, I've contacted Qodana team and they suggested a solution that I hope we'll apply in the near future: https://youtrack.jetbrains.com/issue/PRJ-759. So this is because it's changed.

2021-11-23 08:09 UTC, merged